# Site settings
title: Amirmahdi Mostofinejad
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amostof.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Amirmahdi Mostofinejad
user_description: I am a Ph.D. candidate at the University of Toronto. My background is in mathematical abstraction, formulation, and model inference for biological processes, with my master’s on tumor-induced angiogenesis and my Ph.D. on population dynamics of induced pluripotent stem cells (iPSCs), focusing on their differentiation towards lung progenitors. This includes performing model selection between multiple biologically informed models using sparse experimental data. I also spent a Summer at Genentech working on translational QSP modeling of drug effects on non-small lung cancer cells. There, I developed and validated a pharmacokinetics-pharmacodynamics model for two small molecule drugs undergoing FDA approval, leveraging predictive modeling and simulation tools to optimize drug eﬀicacy and safety. I have extensively utilized Python, Julia, and MATLAB throughout my projects for model preprocessing, numerical solvers, optimization, and visualization, demonstrating a strong ability to adapt quickly and learn new tools.

user_title: PhD Candidate
email: 72.amir@gmail.com
# twitter_username: mahdi_94
# instagram_username: amirmahdimo
# facebook_username: amir.mostofinejad
gscholar_username: E_45_f4AAAAJ
orcid_username: 0000-0003-0783-8757
linkedin_username: amirmahdimo
github_username:  amostof
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

