# Site settings
title: Amirmahdi Mostofinejad
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amostof.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Amirmahdi Mostofinejad
user_description: I am a fourth-year Ph.D. candidate at the University of Toronto. 
My graduate school projects focused on mathematical model development for different biological 
phenomena, with my master’s focusing on tumor-induced angiogenesis (PDE-based) and my Ph.D. on 
neotissue growth in bioreactors (ODE-based). I have also developed a parameter 
estimator for biology-informed deep learning in SDE-based dynamical systems. 
My interests are mathematical modeling, optimization, multiphysics, dynamical systems, deep learning, and physics-informed machine learning.

user_title: PhD Candidate
email: 72.amir@gmail.com
twitter_username: mahdi_94
instagram_username: amirmahdimo
facebook_username: amir.mostofinejad
linkedin_username: amirmahdimo
github_username:  amostof
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

